# Generated by Django 5.0.1 on 2024-01-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CropBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('bank_image', models.ImageField(blank=True, null=True, upload_to='crop_bank_images/')),
            ],
        ),
    ]
