# Generated by Django 5.0.1 on 2024-01-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_remove_cropbank_bank_image_cropbank_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cropbank',
            name='bank_image',
            field=models.ImageField(blank=True, null=True, upload_to='crop_bank_images/'),
        ),
    ]
