# Generated by Django 5.0.1 on 2024-01-30 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_user_adharcard_user_confirm_password_user_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='adharcard',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='driving_license',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='merchant_license',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
